# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    serializer:
        serializer: jms_serializer
    indexes:
        user:
            persistence:
                driver: orm
                model: App\Entity\User
            serializer:
                groups: [elastica]
        tweet:
            persistence:
                driver: orm
                model: App\Entity\Tweet
                provider: ~
                finder: ~
            serializer:
                groups: [elastica]
